
[package]
name = "some-lib-tables"
version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[features]
router = [ "some-lib/router" ]

[dependencies]
env_logger = { workspace = true }
fake = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-storybook = { features = [ "macros" ], workspace = true }
gpui-table = { workspace = true }
gpui-table-component = { workspace = true }
gpui_platform = { workspace = true }
reqwest_client = { workspace = true }
some-lib = { features = [ "client" ], path = "../some-lib" }

[dev-dependencies]
es-fluent = { workspace = true }
gpui = { features = [ "test-support" ], workspace = true }

[lints]
workspace = true
