[workspace]
default-members = [ "examples/some-lib-tables" ]
members = [
  "crates/gpui-table",
  "crates/gpui-table-component",
  "crates/gpui-table-core",
  "crates/gpui-table-derive",
  "crates/gpui-table-prototyping-core",
  "examples/prototyping",
  "examples/some-lib",
  "examples/some-lib-tables",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/gpui-table"
rust-version = "1.88"
version = "0.5.0"

[workspace.dependencies]
anyhow = "1.0"
chrono = "0.4"
crate-paths = "0.2"
darling = "0.23"
derive_more = "2.1"
env_logger = "0.11"
es-fluent = "0.14"
es-fluent-lang = "0.14"
es-fluent-manager-embedded = "0.14"
fake = "4.4"
gpui = { git = "https://github.com/zed-industries/zed", rev = "15d8660748b508b3525d3403e5d172f1a557bfa5" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-storybook = { git = "https://github.com/stayhydated/gpui-storybook" }
gpui-table = { path = "crates/gpui-table", version = "0.5.0" }
gpui-table-component = { path = "crates/gpui-table-component", version = "0.5.0" }
gpui-table-core = { path = "crates/gpui-table-core", version = "0.5.0" }
gpui-table-derive = { path = "crates/gpui-table-derive", version = "0.5.0" }
gpui-table-prototyping-core = { path = "crates/gpui-table-prototyping-core", version = "0.5.0" }
gpui_platform = { features = [
  "font-kit",
  "x11",
  "wayland",
  "runtime_shaders",
], git = "https://github.com/zed-industries/zed", rev = "15d8660748b508b3525d3403e5d172f1a557bfa5" }
gpui_tokio = { git = "https://github.com/zed-industries/zed", rev = "15d8660748b508b3525d3403e5d172f1a557bfa5" }
heck = "0.5.0"
icu = "2.1"
insta = "1.46"
inventory = "0.3"
itertools = "0.14"
jiff = "0.2"
log = "0.4"
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
reqwest = "0.13"
reqwest_client = { git = "https://github.com/zed-industries/zed", rev = "15d8660748b508b3525d3403e5d172f1a557bfa5" }
rust_decimal = "1.40"
serde = "1.0"
serde_json = "1.0"
spacetimedb-lib = "2.0"
strum = "0.28"
syn = "2.0"
thiserror = "2.0"
tokio = "1.49"
tracing-subscriber = "0.3"
trybuild = "1.0"
unicode-segmentation = "1.12"
urlencoding = "2.1"
uuid = "1.21"

[replace]
"https://github.com/zed-industries/zed#gpui@0.2.2" = { git = "https://github.com/zed-industries/zed", rev = "15d8660748b508b3525d3403e5d172f1a557bfa5" }

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
