#[cfg(feature = "story")]
use es_fluent::EsFluent;
use es_fluent::unic_langid::LanguageIdentifier;
use es_fluent::{FluentLabel, FluentMessage};
#[cfg(feature = "story")]
use es_fluent_lang::es_fluent_language;
use gpui_kit::App;
use std::borrow::Borrow;
#[cfg(feature = "story")]
use strum::EnumIter;

es_fluent_manager_embedded::define_i18n_module!();

pub use gpui_es_fluent::{ComponentLocaleError, EmbeddedInitError, I18n};

#[cfg(feature = "story")]
#[es_fluent_language]
#[derive(Clone, Copy, Debug, EnumIter, Eq, EsFluent, PartialEq)]
pub enum Languages {}

/// Errors produced while synchronizing component and table-core locales.
#[derive(Debug, thiserror::Error)]
pub enum LocaleError {
    /// The GPUI component localization bridge rejected the locale.
    #[error(transparent)]
    Component(#[from] ComponentLocaleError),
    /// The process-global table-core localization context rejected the locale.
    #[error(transparent)]
    Core(#[from] gpui_table_core::i18n::LocaleError),
}

fn component_language() -> Result<LanguageIdentifier, ComponentLocaleError> {
    gpui_es_fluent::component_language()
}

fn sync_core_locale(
    language: &LanguageIdentifier,
) -> Result<(), gpui_table_core::i18n::LocaleError> {
    gpui_table_core::i18n::set_locale(language.to_string())
}

/// Initialize table component localization from the active `gpui-kit` locale.
///
/// # Errors
///
/// Returns [`LocaleError`] when the component locale is invalid or either
/// localization context cannot select it.
pub fn init(cx: &mut App) -> Result<(), LocaleError> {
    let language = component_language()?;
    let _linked_module = &GPUI_TABLE_COMPONENT_I18N_MODULE;
    gpui_es_fluent::replace_with_language(cx, language.clone())
        .map_err(ComponentLocaleError::Initialization)?;
    sync_core_locale(&language)?;
    Ok(())
}

/// Select the locale used by built-in table filter components.
///
/// # Errors
///
/// Returns [`LocaleError`] when the locale is invalid or either localization
/// context cannot select it.
pub fn set_locale(cx: &mut App, locale: impl AsRef<str>) -> Result<(), LocaleError> {
    let _linked_module = &GPUI_TABLE_COMPONENT_I18N_MODULE;
    let language = gpui_es_fluent::set_component_locale(cx, locale)?;
    sync_core_locale(&language)?;
    Ok(())
}

/// Applies Storybook's resolved locale to the component and table-core contexts.
///
/// # Errors
///
/// Returns [`LocaleError`] when the locale cannot be applied to either context.
#[cfg(feature = "story")]
pub fn apply_locale(language: Languages, cx: &mut App) -> Result<(), LocaleError> {
    let _linked_module = &GPUI_TABLE_COMPONENT_I18N_MODULE;
    let language: LanguageIdentifier = language.into();
    set_locale(cx, language.to_string())
}

/// Synchronize table component localization with the active `gpui-kit` locale.
///
/// # Errors
///
/// Returns [`LocaleError`] when the component locale is invalid or either
/// localization context cannot select it.
pub fn sync_locale(cx: &impl Borrow<App>) -> Result<(), LocaleError> {
    let language = gpui_es_fluent::sync_component_locale(cx)?;
    sync_core_locale(&language)?;
    Ok(())
}

/// Localize a typed Fluent message through the component embedded i18n context.
///
/// # Panics
///
/// Panics when locale synchronization fails, no localization global is
/// installed, or the typed resource is missing.
pub fn localize_message<T>(cx: &impl Borrow<App>, message: &T) -> String
where
    T: FluentMessage + ?Sized,
{
    sync_locale(cx)
        .unwrap_or_else(|error| panic!("failed to synchronize table component locale: {error}"));
    gpui_es_fluent::localize_message(cx, message)
}

/// Localize a type label generated by `#[derive(es_fluent::EsFluentLabel)]`.
///
/// # Panics
///
/// Panics when locale synchronization fails, no localization global is
/// installed, or the typed label is missing.
pub fn localize_label<T>(cx: &impl Borrow<App>) -> String
where
    T: FluentLabel,
{
    sync_locale(cx)
        .unwrap_or_else(|error| panic!("failed to synchronize table component locale: {error}"));
    gpui_es_fluent::localize_label::<T>(cx)
}

#[cfg(test)]
mod tests {
    use super::*;
    use gpui_kit::gpui;

    #[gpui_kit::test]
    fn component_locale_initialization_and_synchronization_are_repeatable(cx: &mut App) {
        gpui_kit::component::init(cx);
        assert!(init(cx).is_ok());
        assert!(set_locale(cx, "en").is_ok());
        assert!(sync_locale(cx).is_ok());
        assert_eq!(component_language().unwrap().to_string(), "en");
    }

    #[gpui_kit::test]
    fn invalid_component_locale_is_a_typed_error(cx: &mut App) {
        gpui_kit::component::init(cx);
        assert!(matches!(
            set_locale(cx, "not a locale"),
            Err(LocaleError::Component(ComponentLocaleError::InvalidLocale {
                locale,
                ..
            })) if locale == "not a locale"
        ));
    }
}
