use es_fluent::{
    FluentLabel, FluentLocalizer, FluentLocalizerExt as _, FluentMessage, FluentValue,
};
use es_fluent_manager_embedded::{EmbeddedI18n, EmbeddedInitError};
use std::collections::HashMap;
use std::sync::OnceLock;

const FALLBACK_LANGUAGE: &str = "en";

es_fluent_manager_embedded::define_i18n_module!();

static I18N: OnceLock<EmbeddedI18n> = OnceLock::new();

struct FallbackLocalizer;

impl FluentLocalizer for FallbackLocalizer {
    fn localize<'a>(
        &self,
        id: &str,
        _args: Option<&HashMap<&str, FluentValue<'a>>>,
    ) -> Option<String> {
        Some(id.to_string())
    }

    fn localize_in_domain<'a>(
        &self,
        _domain: &str,
        id: &str,
        _args: Option<&HashMap<&str, FluentValue<'a>>>,
    ) -> Option<String> {
        Some(id.to_string())
    }
}

fn fallback_language() -> es_fluent::unic_langid::LanguageIdentifier {
    FALLBACK_LANGUAGE
        .parse()
        .expect("gpui-table-component fallback language must be a valid language identifier")
}

fn i18n() -> Result<&'static EmbeddedI18n, EmbeddedInitError> {
    if I18N.get().is_none() {
        let i18n = EmbeddedI18n::try_new_with_language(fallback_language())?;
        let _ = I18N.set(i18n);
    }

    Ok(I18N
        .get()
        .expect("gpui-table-component i18n should be initialized"))
}

/// Select the locale used by built-in table filter components.
pub fn set_locale(locale: impl AsRef<str>) {
    let locale = locale.as_ref();
    gpui_table_core::i18n::set_locale(locale);

    let Ok(language) = locale.parse::<es_fluent::unic_langid::LanguageIdentifier>() else {
        return;
    };

    if let Ok(i18n) = i18n() {
        let _ = i18n.select_language(language);
    }
}

/// Synchronize table component localization with the active `gpui-component` locale.
pub fn sync_locale() {
    let locale = gpui_component::locale().to_string();
    set_locale(&locale);
}

/// Localize a typed Fluent message through the component embedded i18n context.
pub fn localize_message<T>(message: &T) -> String
where
    T: FluentMessage + ?Sized,
{
    sync_locale();

    match i18n() {
        Ok(i18n) => i18n.localize_message(message),
        Err(_) => FallbackLocalizer.localize_message(message),
    }
}

/// Localize a type label generated by `#[derive(es_fluent::EsFluentLabel)]`.
pub fn localize_label<T>() -> String
where
    T: FluentLabel,
{
    sync_locale();

    match i18n() {
        Ok(i18n) => T::localize_label(i18n),
        Err(_) => T::localize_label(&FallbackLocalizer),
    }
}
