#[cfg(feature = "story")]
use es_fluent::EsFluent;
use es_fluent::{FluentLabel, FluentMessage};
#[cfg(feature = "story")]
use es_fluent_lang::es_fluent_language;
use gpui::App;
use std::borrow::Borrow;
#[cfg(feature = "story")]
use strum::EnumIter;

const FALLBACK_LANGUAGE: &str = "en";

es_fluent_manager_embedded::define_i18n_module!();

pub use gpui_es_fluent::{EmbeddedInitError, I18n};

#[cfg(feature = "story")]
#[es_fluent_language]
#[derive(Clone, Copy, Debug, EnumIter, Eq, EsFluent, PartialEq)]
pub enum Languages {}

fn component_language() -> es_fluent::unic_langid::LanguageIdentifier {
    gpui_es_fluent::component_language(FALLBACK_LANGUAGE)
}

fn sync_core_locale(language: &es_fluent::unic_langid::LanguageIdentifier) {
    gpui_table_core::i18n::set_locale(language.to_string());
}

/// Initialize table component localization from the active `gpui-component` locale.
pub fn init(cx: &mut App) -> Result<(), EmbeddedInitError> {
    let language = component_language();
    sync_core_locale(&language);
    gpui_es_fluent::replace_with_language(cx, language)
}

/// Select the locale used by built-in table filter components.
pub fn set_locale(cx: &mut App, locale: impl AsRef<str>) -> Result<(), EmbeddedInitError> {
    let language = gpui_es_fluent::set_component_locale(cx, locale, FALLBACK_LANGUAGE)?;
    sync_core_locale(&language);
    Ok(())
}

/// Synchronize table component localization with the active `gpui-component` locale.
pub fn sync_locale(cx: &impl Borrow<App>) {
    let language = gpui_es_fluent::sync_component_locale(cx, FALLBACK_LANGUAGE);
    sync_core_locale(&language);
}

/// Localize a typed Fluent message through the component embedded i18n context.
pub fn localize_message<T>(cx: &impl Borrow<App>, message: &T) -> String
where
    T: FluentMessage + ?Sized,
{
    sync_locale(cx);
    cx.borrow()
        .try_global::<I18n>()
        .map(|i18n| i18n.localize_message(message))
        .unwrap_or_else(|| fallback_message(message))
}

/// Localize a type label generated by `#[derive(es_fluent::EsFluentLabel)]`.
pub fn localize_label<T>(cx: &impl Borrow<App>) -> String
where
    T: FluentLabel,
{
    sync_locale(cx);
    cx.borrow()
        .try_global::<I18n>()
        .map(I18n::localize_label::<T>)
        .unwrap_or_else(fallback_label::<T>)
}

/// Render a typed Fluent message without consulting GPUI app state.
pub fn fallback_message<T>(message: &T) -> String
where
    T: FluentMessage + ?Sized,
{
    gpui_table_core::i18n::set_locale(gpui_component::locale().to_string());
    gpui_table_core::i18n::localize_message(message)
}

/// Render a type label without consulting process-global locale state.
///
/// This is intended for truly context-free surfaces. Runtime UI and Storybook
/// metadata with access to `gpui::App` should use `localize_label`.
pub fn fallback_label<T>() -> String
where
    T: FluentLabel,
{
    gpui_es_fluent::fallback_label::<T>()
}
