use gpui::{AnyElement, App, Div, InteractiveElement as _, IntoElement, Stateful, Window, div};
use gpui_component::table::Column;

/// A value that can be displayed in a table cell.
pub trait TableCell {
    fn draw(&self, window: &mut Window, cx: &mut App) -> AnyElement;
}

macro_rules! impl_table_cell_display {
    ($($t:ty),* $(,)?) => {
        $(
            impl TableCell for $t {
                fn draw(&self, _window: &mut Window, _cx: &mut App) -> AnyElement {
                    self.to_string().into_any_element()
                }
            }
        )*
    };
}

macro_rules! impl_table_cell_float {
    ($($t:ty),* $(,)?) => {
        $(
            impl TableCell for $t {
                fn draw(&self, _window: &mut Window, _cx: &mut App) -> AnyElement {
                    format!("{:.2}", self).into_any_element()
                }
            }
        )*
    };
}

impl_table_cell_display!(String, &str, usize, u8, u16, u32, u64, i8, i16, i32, i64);
impl_table_cell_float!(f32, f64);

impl TableCell for bool {
    fn draw(&self, _window: &mut Window, _cx: &mut App) -> AnyElement {
        (if *self { "✓" } else { "✗" }).into_any_element()
    }
}

/// Metadata for a table row type.
///
/// This trait describes the structure of the row (columns, ID, title)
/// and provides a way to extract cell values.
pub trait TableRowMeta {
    /// Unique identifier for this row type.
    const TABLE_ID: &'static str;

    /// Human-readable title for the table.
    const TABLE_TITLE: &'static str;

    /// Returns the table title. This can be overridden to provide dynamic
    /// titles, for example from localization libraries.
    fn table_title() -> String {
        Self::TABLE_TITLE.to_string()
    }

    /// Returns the column definitions for this row type.
    fn table_columns() -> &'static [Column];

    /// Returns the value for a specific column index.
    fn cell_value(&self, col_ix: usize) -> Box<dyn TableCell + '_>;
}

/// Styling hooks for a table row.
///
/// This trait allows customizing how rows and cells are rendered.
/// The `NamedTableRow` derive macro generates a default implementation
/// that uses `default_render_cell` and `default_render_row`.
pub trait TableRowStyle: TableRowMeta {
    /// The type representing the columns of the table.
    /// Usually an enum generated by the derive macro.
    type ColumnId: Into<usize> + From<usize>;

    /// Renders a single cell.
    fn render_table_cell(
        &self,
        col: Self::ColumnId,
        window: &mut Window,
        cx: &mut App,
    ) -> AnyElement;

    /// Renders the row container.
    fn render_table_row(&self, row_ix: usize, window: &mut Window, cx: &mut App) -> Stateful<Div> {
        default_render_row(row_ix, window, cx)
    }
}

/// Default implementation for rendering a cell.
pub fn default_render_cell<R: TableRowMeta + ?Sized>(
    row: &R,
    col_ix: usize,
    window: &mut Window,
    cx: &mut App,
) -> impl IntoElement {
    row.cell_value(col_ix).draw(window, cx)
}

/// Default implementation for rendering a row.
pub fn default_render_row(row_ix: usize, _window: &mut Window, _cx: &mut App) -> Stateful<Div> {
    div().id(row_ix)
}
