// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::spacetime_mutation_type::SpacetimeMutation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpacetimeEvent {
    pub id: u64,
    pub table_name: String,
    pub sender: __sdk::Identity,
    pub connection_id: Option<__sdk::ConnectionId>,
    pub mutation: SpacetimeMutation,
    pub committed_at: __sdk::Timestamp,
    pub reducer: String,
}

impl __sdk::InModule for SpacetimeEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpacetimeEvent`.
///
/// Provides typed access to columns for query building.
pub struct SpacetimeEventCols {
    pub id: __sdk::__query_builder::Col<SpacetimeEvent, u64>,
    pub table_name: __sdk::__query_builder::Col<SpacetimeEvent, String>,
    pub sender: __sdk::__query_builder::Col<SpacetimeEvent, __sdk::Identity>,
    pub connection_id: __sdk::__query_builder::Col<SpacetimeEvent, Option<__sdk::ConnectionId>>,
    pub mutation: __sdk::__query_builder::Col<SpacetimeEvent, SpacetimeMutation>,
    pub committed_at: __sdk::__query_builder::Col<SpacetimeEvent, __sdk::Timestamp>,
    pub reducer: __sdk::__query_builder::Col<SpacetimeEvent, String>,
}

impl __sdk::__query_builder::HasCols for SpacetimeEvent {
    type Cols = SpacetimeEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpacetimeEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            table_name: __sdk::__query_builder::Col::new(table_name, "table_name"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            connection_id: __sdk::__query_builder::Col::new(table_name, "connection_id"),
            mutation: __sdk::__query_builder::Col::new(table_name, "mutation"),
            committed_at: __sdk::__query_builder::Col::new(table_name, "committed_at"),
            reducer: __sdk::__query_builder::Col::new(table_name, "reducer"),
        }
    }
}

/// Indexed column accessor struct for the table `SpacetimeEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpacetimeEventIxCols {}

impl __sdk::__query_builder::HasIxCols for SpacetimeEvent {
    type IxCols = SpacetimeEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpacetimeEventIxCols {}
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpacetimeEvent {}
