// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(Clone, Debug, __lib::de::Deserialize, PartialEq, __lib::ser::Serialize)]
#[sats(crate = __lib)]
#[derive(Copy, Eq, Hash)]
pub enum SpacetimeMutation {
    Insert,

    Update,

    Delete,
}

impl __sdk::InModule for SpacetimeMutation {
    type Module = super::RemoteModule;
}
