// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::spacetime_event_type::SpacetimeEvent;
use super::spacetime_mutation_type::SpacetimeMutation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `spacetime_event`.
///
/// Obtain a handle from the [`SpacetimeEventTableAccess::spacetime_event`] method on [`super::RemoteTables`],
/// like `ctx.db.spacetime_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.spacetime_event().on_insert(...)`.
pub struct SpacetimeEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpacetimeEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `spacetime_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpacetimeEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpacetimeEventTableHandle`], which mediates access to the table `spacetime_event`.
    fn spacetime_event(&self) -> SpacetimeEventTableHandle<'_>;
}

impl SpacetimeEventTableAccess for super::RemoteTables {
    fn spacetime_event(&self) -> SpacetimeEventTableHandle<'_> {
        SpacetimeEventTableHandle {
            imp: self.imp.get_table::<SpacetimeEvent>("spacetime_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpacetimeEventInsertCallbackId(__sdk::CallbackId);
pub struct SpacetimeEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpacetimeEventTableHandle<'ctx> {
    type Row = SpacetimeEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpacetimeEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpacetimeEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpacetimeEventInsertCallbackId {
        SpacetimeEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpacetimeEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpacetimeEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpacetimeEventDeleteCallbackId {
        SpacetimeEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpacetimeEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpacetimeEvent>("spacetime_event");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpacetimeEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpacetimeEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpacetimeEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait spacetime_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpacetimeEvent`.
    fn spacetime_event(&self) -> __sdk::__query_builder::Table<SpacetimeEvent>;
}

impl spacetime_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn spacetime_event(&self) -> __sdk::__query_builder::Table<SpacetimeEvent> {
        __sdk::__query_builder::Table::new("spacetime_event")
    }
}
