[package]
name = "some-lib"
version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[lib]
crate-type = [ "cdylib", "lib" ]

[features]
client = [
  "dep:chrono",
  "dep:es-fluent",
  "dep:es-fluent-lang",
  "dep:es-fluent-manager-embedded",
  "dep:fake",
  "dep:gpui",
  "dep:gpui-component",
  "dep:gpui-table",
  "dep:gpui-table-component",
  "dep:rust_decimal",
  "dep:serde",
  "dep:strum",
  "dep:uuid",
]
db = [  ]
default = [  ]
router = [ "client" ]

[dependencies]
chrono = { optional = true, workspace = true }
es-fluent = { optional = true, workspace = true }
es-fluent-lang = { optional = true, workspace = true }
es-fluent-manager-embedded = { optional = true, workspace = true }
fake = { features = [
  "derive",
  "uuid",
  "random_color",
  "chrono",
  "rust_decimal",
], optional = true, workspace = true }
gpui = { optional = true, workspace = true }
gpui-component = { optional = true, workspace = true }
gpui-table = { features = [
  "fluent",
  "inventory",
  "rust_decimal",
  "chrono",
], optional = true, workspace = true }
gpui-table-component = { features = [
  "chrono",
  "rust_decimal",
], optional = true, workspace = true }
rust_decimal = { optional = true, workspace = true }
serde = { features = [ "derive" ], optional = true, workspace = true }
strum = { optional = true, workspace = true }
uuid = { optional = true, workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }

[lints]
workspace = true
