use std::cell::RefCell;
use std::rc::Rc;
use std::sync::Arc;

use es_fluent::ThisFtl as _;
use fake::{Fake, Faker};
use gpui::{
    App, AppContext as _, Context, Entity, Focusable, ParentElement, Render, Styled, Subscription,
    Window, prelude::FluentBuilder,
};
use gpui_component::{
    ActiveTheme, h_flex,
    table::{Table, TableState},
    v_flex,
};
use some_lib::structs::filter_showcase::{
    FilterShowcase, FilterShowcaseFilterEntities, FilterShowcaseTableDelegate,
};

#[gpui_storybook::story_init]
pub fn init(_cx: &mut App) {}

#[gpui_storybook::story("fake")]
pub struct FilterShowcaseStory {
    table: Entity<TableState<FilterShowcaseTableDelegate>>,
    /// All filter UI entities (generated by macro)
    filters: FilterShowcaseFilterEntities,
    /// The complete data pool (generated once, never changes)
    all_data: Rc<Vec<FilterShowcase>>,
    _subscription: Subscription,
}

impl gpui_storybook::Story for FilterShowcaseStory {
    fn title() -> String {
        FilterShowcase::this_ftl()
    }

    fn new_view(window: &mut Window, cx: &mut App) -> Entity<impl Render + Focusable> {
        Self::view(window, cx)
    }
}

impl Focusable for FilterShowcaseStory {
    fn focus_handle(&self, cx: &gpui::App) -> gpui::FocusHandle {
        self.table.focus_handle(cx)
    }
}

impl FilterShowcaseStory {
    pub fn view(window: &mut Window, cx: &mut App) -> Entity<Self> {
        cx.new(|cx| Self::new(window, cx))
    }

    fn new(window: &mut Window, cx: &mut Context<Self>) -> Self {
        // Generate complete data pool once at startup
        let all_data: Rc<Vec<FilterShowcase>> = Rc::new((0..500).map(|_| Faker.fake()).collect());

        // Initialize delegate with the full data set
        let delegate = FilterShowcaseTableDelegate::with_data_pool((*all_data).clone());
        let table = cx.new(|cx| TableState::new(delegate, window, cx));

        // Create holders for the callback to access data pool and filters
        let data_pool_for_callback = all_data.clone();
        let filter_holder: Rc<RefCell<Option<FilterShowcaseFilterEntities>>> =
            Rc::new(RefCell::new(None));
        let filter_holder_for_callback = filter_holder.clone();
        let table_for_reload = table.clone();

        // Build all filter entities with client-side filtering callback
        let filters = FilterShowcaseFilterEntities::build(
            Some(Arc::new(move |window, cx| {
                if let Some(ref filter_entities) = *filter_holder_for_callback.borrow() {
                    // Read all filter values using the generated read_values method
                    let filter_values = filter_entities.read_values(cx);

                    // Apply filters to the stable data pool
                    table_for_reload.update(cx, |table, cx| {
                        table.delegate_mut().apply_filters(
                            &data_pool_for_callback,
                            &filter_values,
                            window,
                            cx,
                        );
                    });
                }
            })),
            cx,
        );

        // Populate the holder so the callback can access filter values
        *filter_holder.borrow_mut() = Some(filters.clone());

        let _subscription = cx.observe(&table, |_this, _, cx| {
            cx.notify();
        });

        Self {
            table,
            filters,
            all_data,
            _subscription,
        }
    }
}

impl Render for FilterShowcaseStory {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl gpui::IntoElement {
        // Get sample filter values to display (just showing a few for demo)
        let name_filter = self.filters.name_value(cx);
        let priority_filter = self.filters.priority_value(cx);
        let category_filter = self.filters.category_value(cx);
        let age_filter = self.filters.age_value(cx);

        let table = self.table.read(cx);
        let delegate = table.delegate();
        let row_count = delegate.rows.len();
        let total_count = self.all_data.len();

        let has_any_filter = !name_filter.is_empty()
            || !priority_filter.is_empty()
            || !category_filter.is_empty()
            || age_filter.0.is_some()
            || age_filter.1.is_some();

        v_flex()
            .size_full()
            .gap_4()
            .p_4()
            // Text Filters row - using generated helper
            .child(
                v_flex()
                    .gap_1()
                    .child(
                        gpui::div()
                            .text_xs()
                            .text_color(cx.theme().muted_foreground)
                            .child("Text Filters"),
                    )
                    .child(self.filters.text_filters()),
            )
            // Number Range Filters row - using generated helper
            .child(
                v_flex()
                    .gap_1()
                    .child(
                        gpui::div()
                            .text_xs()
                            .text_color(cx.theme().muted_foreground)
                            .child("Number Range Filters"),
                    )
                    .child(self.filters.number_filters()),
            )
            // Faceted Filters row - using generated helper
            .child(
                v_flex()
                    .gap_1()
                    .child(
                        gpui::div()
                            .text_xs()
                            .text_color(cx.theme().muted_foreground)
                            .child("Faceted Filters"),
                    )
                    .child(self.filters.faceted_filters()),
            )
            // Date Range Filters row - using generated helper
            .child(
                v_flex()
                    .gap_1()
                    .child(
                        gpui::div()
                            .text_xs()
                            .text_color(cx.theme().muted_foreground)
                            .child("Date Range Filters"),
                    )
                    .child(self.filters.date_filters()),
            )
            // Active filter values display
            .when(has_any_filter, |this| {
                this.child(
                    v_flex()
                        .gap_1()
                        .child(
                            gpui::div()
                                .text_xs()
                                .font_weight(gpui::FontWeight::SEMIBOLD)
                                .text_color(cx.theme().muted_foreground)
                                .child("Active Filter Values"),
                        )
                        .child(
                            h_flex()
                                .gap_2()
                                .text_xs()
                                .text_color(cx.theme().muted_foreground)
                                .flex_wrap()
                                .when(!name_filter.is_empty(), |c| {
                                    c.child(format!("name: \"{}\"", name_filter))
                                })
                                .when(!priority_filter.is_empty(), |c| {
                                    c.child(format!("priority: {:?}", priority_filter))
                                })
                                .when(!category_filter.is_empty(), |c| {
                                    c.child(format!("category: {:?}", category_filter))
                                })
                                .when(age_filter.0.is_some() || age_filter.1.is_some(), |c| {
                                    c.child(format!("age: {:?}", age_filter))
                                })
                        )
                )
            })
            // Status bar
            .child(
                h_flex()
                    .gap_4()
                    .child(format!("Showing: {} / {} rows", row_count, total_count))
                    .child("Client-side filtering"),
            )
            // Table
            .child(
                Table::new(&self.table)
                    .stripe(true)
                    .scrollbar_visible(true, true),
            )
    }
}
