use std::sync::Arc;

use es_fluent::ThisFtl as _;
use gpui::{
    App, AppContext as _, Context, Entity, Focusable, ParentElement, Render, Styled, Subscription,
    Window,
};
use gpui_component::{
    ActiveTheme, h_flex,
    table::{Table, TableState},
    v_flex,
};
use some_lib::structs::product::{Product, ProductFilterEntities, ProductTableDelegate};

#[gpui_storybook::story_init]
pub fn init(_cx: &mut App) {}

#[gpui_storybook::story]
pub struct ProductStory {
    table: Entity<TableState<ProductTableDelegate>>,
    /// All filter UI entities (generated by macro)
    filters: ProductFilterEntities,
    _subscription: Subscription,
}

impl gpui_storybook::Story for ProductStory {
    fn title() -> String {
        Product::this_ftl()
    }

    fn new_view(window: &mut Window, cx: &mut App) -> Entity<impl Render + Focusable> {
        Self::view(window, cx)
    }
}

impl Focusable for ProductStory {
    fn focus_handle(&self, cx: &gpui::App) -> gpui::FocusHandle {
        self.table.focus_handle(cx)
    }
}

impl ProductStory {
    pub fn view(window: &mut Window, cx: &mut App) -> Entity<Self> {
        cx.new(|cx| Self::new(window, cx))
    }

    fn new(window: &mut Window, cx: &mut Context<Self>) -> Self {
        let delegate = ProductTableDelegate::new(vec![]);
        let table = cx.new(|cx| TableState::new(delegate, window, cx));

        // Trigger initial load
        table.update(cx, |table, cx| {
            table.delegate_mut().load_more_products(window, cx);
        });

        // Build all filter entities using the generated builder
        // For server-side filtering, pass an on_change callback that triggers reload
        let table_for_reload = table.clone();
        let filters = ProductFilterEntities::build(
            &table,
            Some(Arc::new(move |window, cx| {
                table_for_reload.update(cx, |table, cx| {
                    table.delegate_mut().reset_and_reload(window, cx);
                });
            })),
            cx,
        );

        let _subscription = cx.observe(&table, |_, _, cx| cx.notify());

        Self {
            table,
            filters,
            _subscription,
        }
    }
}

impl Render for ProductStory {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl gpui::IntoElement {
        let table = self.table.read(cx);
        let delegate = table.delegate();

        v_flex()
            .size_full()
            .gap_4()
            .p_4()
            // Server-side filters row - using generated all_filters helper
            .child(
                v_flex()
                    .gap_1()
                    .child(
                        gpui::div()
                            .text_xs()
                            .text_color(cx.theme().muted_foreground)
                            .child("Server-Side Filters"),
                    )
                    .child(self.filters.all_filters()),
            )
            // Status bar
            .child(
                h_flex()
                    .gap_4()
                    .child(format!("Products Loaded: {}", delegate.rows.len()))
                    .child(if delegate.loading {
                        "Fetching from DummyJSON..."
                    } else {
                        "Idle"
                    })
                    .child(if delegate.eof {
                        "All data loaded"
                    } else {
                        "Scroll for more"
                    }),
            )
            // Table
            .child(
                Table::new(&self.table)
                    .stripe(true)
                    .scrollbar_visible(true, true),
            )
    }
}
