use std::cell::RefCell;
use std::rc::Rc;

use es_fluent::ThisFtl as _;
use gpui::{
    App, AppContext as _, Context, Entity, Focusable, ParentElement, Render, Styled, Subscription,
    Window, prelude::FluentBuilder,
};
use gpui_component::{
    ActiveTheme, h_flex,
    table::{Table, TableState},
    v_flex,
};
use gpui_table::TableDataLoader as _;
use gpui_table::filter::{FilterEntitiesExt as _, FilterValuesExt as _};
use gpui_table_components::TableStatusBar;
use some_lib::structs::product::{Product, ProductFilterEntities, ProductTableDelegate};

#[gpui_storybook::story_init]
pub fn init(_cx: &mut App) {}

#[gpui_storybook::story("api")]
pub struct ProductTableStory {
    table: Entity<TableState<ProductTableDelegate>>,
    /// All filter UI entities (generated by macro)
    filters: ProductFilterEntities,
    _subscription: Subscription,
}

impl gpui_storybook::Story for ProductTableStory {
    fn title() -> String {
        Product::this_ftl()
    }

    fn new_view(window: &mut Window, cx: &mut App) -> Entity<impl Render + Focusable> {
        Self::view(window, cx)
    }
}

impl Focusable for ProductTableStory {
    fn focus_handle(&self, cx: &gpui::App) -> gpui::FocusHandle {
        self.table.focus_handle(cx)
    }
}

impl ProductTableStory {
    pub fn view(window: &mut Window, cx: &mut App) -> Entity<Self> {
        cx.new(|cx| Self::new(window, cx))
    }

    fn new(window: &mut Window, cx: &mut Context<Self>) -> Self {
        let delegate = ProductTableDelegate::new(vec![]);
        let table = cx.new(|cx| TableState::new(delegate, window, cx));

        // Trigger initial load
        table.update(cx, |table, cx| {
            table.delegate_mut().load_data(window, cx);
        });

        // Use a holder pattern to allow the callback to access filter values
        // The holder is populated after filter creation
        let filter_holder: Rc<RefCell<Option<ProductFilterEntities>>> = Rc::new(RefCell::new(None));
        let filter_holder_for_callback = filter_holder.clone();
        let table_for_reload = table.clone();

        // Build all filter entities with a callback that reads current filter values
        let filters = ProductFilterEntities::build(
            Some(Rc::new(move |window, cx| {
                if let Some(ref filters) = *filter_holder_for_callback.borrow() {
                    let filter_values = filters.read_values(cx);

                    table_for_reload.update(cx, |table, cx| {
                        table.delegate_mut().reset_and_reload_with_filters(
                            filter_values,
                            window,
                            cx,
                        );
                    });
                }
            })),
            cx,
        );

        // Populate the holder so the callback can access filter values
        *filter_holder.borrow_mut() = Some(filters.clone());

        let _subscription = cx.observe(&table, |_, _, cx| cx.notify());

        Self {
            table,
            filters,
            _subscription,
        }
    }
}

impl Render for ProductTableStory {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl gpui::IntoElement {
        // Capture values before reading table
        let filters = self.filters.read_values(cx);

        let table = self.table.read(cx);
        let delegate = table.delegate();
        let row_count = delegate.rows.len();
        let loading = delegate.loading;
        let eof = delegate.eof;

        v_flex()
            .size_full()
            .gap_4()
            .p_4()
            // Server-side filters row - using generated all_filters helper
            .child(
                v_flex()
                    .gap_1()
                    .child(
                        gpui::div()
                            .text_xs()
                            .text_color(cx.theme().muted_foreground)
                            .child("Server-Side Filters (values passed to API)"),
                    )
                    .child(self.filters.all_filters()),
            )
            // Current filter values debug display
            .when(filters.has_active_filters(), |this| {
                this.child(
                    h_flex()
                        .gap_2()
                        .text_xs()
                        .text_color(cx.theme().muted_foreground)
                        .when(filters.title.is_active(), |c| c.child(format!("title: \"{}\"", filters.title)))
                        .when(filters.category.is_active(), |c| c.child(format!("category: {:?}", filters.category)))
                )
            })
            .child(TableStatusBar::new(row_count, loading, eof))
            // Table
            .child(
                Table::new(&self.table)
                    .stripe(true)
                    .scrollbar_visible(true, true),
            )
    }
}
