[package]
name = "mcp-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Unlicense"
publish = false

[dependencies]
chrono = { workspace = true }
gpui-kit = { workspace = true }
gpui-table = { features = [ "mcp", "rust_decimal" ], workspace = true }
gpui-table-component = { features = [ "chrono", "mcp", "rust_decimal" ], workspace = true }
serde = { features = [ "derive" ], workspace = true }

[package.metadata.cargo-machete]
ignored = [ "gpui-kit" ]

[lints]
workspace = true
