[package]
name = "prototyping"
version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
anyhow = { workspace = true }
gpui-table = { features = [ "inventory", "fluent", "rust_decimal", "chrono" ], workspace = true }
gpui-table-prototyping-core = { workspace = true }
heck = { workspace = true }
inventory = { workspace = true }
prettyplease = { workspace = true }
quote = { workspace = true }
some-lib = { features = [ "client" ], path = "../some-lib" }
syn = { features = [ "full", "parsing" ], workspace = true }
